apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-${environment}
spec:
  acme:
    server: ${acme_server}
    email: ${email}
    privateKeySecretRef:
      name: letsencrypt-${environment}
    solvers:
    - http01:
        ingress:
          class: nginx
